### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by MaddinMade** [KRTirtho/metadata_god#1]
I'm just trying to write the duration to an audio file but the following error is thrown every time:

```
flutter: Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': dlsym(RTLD_DEFAULT, store_dart_post_cobject): symbol not found
flutter: 
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      RustWire._store_dart_post_cobjectPtr (package:metadata_god/src/bridge_generated.dart:540:62)
#2      RustWire._store_dart_post_cobjectPtr (package:metadata_god/src/bridge_generated.dart)
#3      RustWire._store_dart_post_cobject (package:metadata_god/src/bridge_generated.dart:543:7)
#4      RustWire._store_dart_post_cobject (package:metadata_god/src/bridge_generated.dart)
#5      RustWire.store_dart_post_cobject (package:metadata_god/src/bridge_generated.dart:534:12)
#6      StoreDartPostCObjectExt.storeDartPostCObject (package:flutter_rust_bridge/src/ffi/io.dart:15:5)
#7      FlutterRustBridgeBase._setUpRustToDartComm (package:flutter_rust_bridge/src/basic.dart:39:11)
#8      new FlutterRustBridgeBase (package:flutter_rust_bridge/src/basic.dart:22:5)
#9      new RustImpl.raw (package:metadata_god/src/bridge_generated.dart:77:34)
#10     new RustImpl (package:metadata_god/src/bridge_generated.d<…>
flutter: ----------------------------------------------------
```

Version: 0.2.0
Platform: IPhone Simulator
OS: iOS 16

EDIT: Sorry, didn't see, that iOS ist not supported. Is iOS support planned for the future?

**Comment by KRTirtho** [comment]
I wish I could add support, but Apple :face_exhaling: 
I need someone who can add iOS support
