### ISSUE TITLE
Unable to build application when using this plugin

### ISSUE THREAD

**Issue by dannyglover** [KRTirtho/metadata_god#24]
I'm on Fedora Linux 38, here's the output of `flutter --version`

```
Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (2 days ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0
```

Here is the error log generated by `flutter run -v`

```
package:myapp/main.dart
[   +1 ms] [ +861 ms] ../../../../.pub-cache/hosted/pub.dev/metadata_god-0.5.0/lib/src/bridge_generated.dart:86:57: Error: Required named parameter 'parseErrorData' must be provided.
[   +1 ms] [   +1 ms]     return _platform.executeNormal(FlutterRustBridgeTask(
[        ] [        ]                                                         ^
[   +2 ms] [        ] ../../../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.1/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   const FlutterRustBridgeTask({
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^
[        ] [   +1 ms] ../../../../.pub-cache/hosted/pub.dev/metadata_god-0.5.0/lib/src/bridge_generated.dart:105:57: Error: Required named parameter 'parseErrorData' must be provided.
[        ] [        ]     return _platform.executeNormal(FlutterRustBridgeTask(
[        ] [        ]                                                         ^
[        ] [        ] ../../../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.1/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   const FlutterRustBridgeTask({
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^
[        ] [ +300 ms] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +2 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:256:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
[        ]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
[        ]            <asynchronous suspension>
[        ]            #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
[        ]            <asynchronous suspension>
[        ]            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
[        ]            <asynchronous suspension>
[        ]            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
[        ]            <asynchronous suspension>
[        ]            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     main (package:flutter_tools/executable.dart:90:3)
[        ]            <asynchronous suspension>
[        ] [   +8 ms] "flutter assemble" took 1,718ms.
[        ] [   +3 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:332:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:90:3)
[        ]            <asynchronous suspension>
[        ] [ +104 ms] ensureAnalyticsSent: 97ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[   +9 ms] Building Linux application... (completed in 2,272ms)
[+1192 ms] ../../../../.pub-cache/hosted/pub.dev/metadata_god-0.5.0/lib/src/bridge_generated.dart:86:57: Error: Required named parameter 'parseErrorData' must be provided.
[        ]     return _platform.executeNormal(FlutterRustBridgeTask(
[        ]                                                         ^
[        ] ../../../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.1/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
[        ]   const FlutterRustBridgeTask({
[        ]         ^^^^^^^^^^^^^^^^^^^^^
[   +2 ms] ../../../../.pub-cache/hosted/pub.dev/metadata_god-0.5.0/lib/src/bridge_generated.dart:105:57: Error: Required named parameter 'parseErrorData' must be provided.
[        ]     return _platform.executeNormal(FlutterRustBridgeTask(
[        ]                                                         ^
[        ] ../../../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.1/lib/src/basic.dart:179:9: Context: Found this candidate, but the arguments don't match.
[        ]   const FlutterRustBridgeTask({
[        ]         ^^^^^^^^^^^^^^^^^^^^^
[+4648 ms] Exception: Build process failed
[   +3 ms] "flutter run" took 8,660ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

**Comment by ruwiss** [comment]
Same error -,-

**Comment by max-anders** [comment]
same
